version: '3.8'

services:
  postgre:
    image: postgres:17
    container_name: rpg_pg
    volumes:
      - rpg_data:/var/lib/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:8
    restart: unless-stopped



volumes:
  rpg_data: