spring.application.name=rpg-api

spring.datasource.url=jdbc:postgresql://localhost:5432/rpg-dnd
spring.datasource.username=joao
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


server.address=0.0.0.0
server.port=8080